FROM python:3.11-slim
WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y nodejs npm && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Install esbuild for bundling
RUN npm install -g esbuild

# Copy your application
COPY . .

# Expose app port
EXPOSE 8000

# Run uvicorn for dev
COPY start.sh .
CMD ["./start.sh"]