services:
  bajeti_app:
    build: .
    container_name: bajeti_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data                # persist entire data folder
      - ./app/templates:/app/app/templates   # hot-reload templates
      - ./app/static:/app/app/static         # static files
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bajeti-networks
    
  # Cloudflare tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    user: "0"  # run as root so it can read certs
    command: tunnel --config /root/.cloudflared/config.yml run bajeti
    volumes:
      - ./cloudflared:/root/.cloudflared
    depends_on:
      - bajeti_app
    networks:
      - bajeti-net

networks:
  bajeti-net:
    driver: bridge
