services:
  bajeti_app:
    build: .
    container_name: bajeti_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data                # persist entire data folder
      - ./app/templates:/app/app/templates   # hot-reload templates
      - ./app/static:/app/app/static         # static files
    env_file:
      - .env
    restart: unless-stopped
