services:
  bajeti_app:
    build: .
    container_name: bajeti_app
    ports:
      - "8000:8000"
    volumes:
      - ./bajeti.db:/app/bajeti.db   # persist sqlite db
      - ./app/templates:/app/app/templates   # hot-reload templates
      - ./app/static:/app/app/static         # static files
    env_file:
      - .env
    restart: unless-stopped
  ngrok:
    image: wernight/ngrok
    container_name: bajeti_ngrok
    command: http bajeti_app:8000
    depends_on:
      - bajeti_app
    env_file:
      - .env