services:
  bajeti_app:
    build: .
    container_name: bajeti_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app/templates:/app/app/templates
      - ./app/static:/app/app/static
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bajeti-net
    command: >
      bash -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000"
    
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    user: "0"
    command: tunnel --config /root/.cloudflared/config.yml run bajeti
    volumes:
      - ./cloudflared:/root/.cloudflared
    depends_on:
      - bajeti_app
    networks:
      - bajeti-net

networks:
  bajeti-net:
    driver: bridge
