"""Make Category unique per user

Revision ID: 5ad9aed81e52
Revises: 922afb67a64e
Create Date: 2025-11-08 04:42:43.286908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0cfc8ae7830'
down_revision: Union[str, Sequence[str], None] = '922afb67a64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'uq_user_category_name', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_category_name', type_='unique')

    # ### end Alembic commands ###
