name: Deploy to Raspberry Pi

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:  # optional manual trigger

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM builds)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push bajeti_app image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bajeti_app:latest
          platforms: linux/arm64

      - name: SSH into Raspberry Pi and update bajeti_app
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /home/${{ secrets.PI_USER }}/bajeti

            echo "Pulling latest image..."
            docker compose pull bajeti_app

            echo "Recreating only bajeti_app..."
            docker compose up -d bajeti_app

            echo "Cleaning up old, unused images..."
            docker image prune -f
