name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          echo "Writing .env file..."
          cat <<EOF > .env
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          ALGORITHM=${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          API_BASE_URL=${{ secrets.API_BASE_URL }}
          API_SERVER=${{ secrets.API_SERVER }}
          ENVIRONMENT=${{ secrets.ENVIRONMENT }}
          EOF

      - name: Build and deploy containers
        run: |
          echo "Pulling latest images and rebuilding app..."
          docker compose build bajeti_app
          docker compose up -d bajeti_app

      - name: Clean up unused images
        run: docker image prune -f
