name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Go to project directory
        run: cd /home/joshuamangi/projects/bajeti

      - name: Pull latest code
        run: |
          cd /home/joshuamangi/projects/bajeti
          git fetch origin main
          git reset --hard origin/main

      - name: Load environment variables
        run: |
          cd /home/joshuamangi/projects/bajeti
          echo "Writing .env file..."
          cat <<EOF > .env
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          ALGORITHM=${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          API_BASE_URL=${{ secrets.API_BASE_URL }}
          API_SERVER=${{ secrets.API_SERVER }}
          ENVIRONMENT=${{ secrets.ENVIRONMENT }}
          EOF

      - name: Build and deploy containers
        run: |
          cd /home/joshuamangi/projects/bajeti
          # Stop and remove old container
          docker compose down bajeti_app || true
          # Rebuild with no cache to ensure latest changes
          docker compose build --no-cache bajeti_app
          docker compose up -d bajeti_app

      - name: Clean up
        run: docker image prune -f